### ISSUE TITLE
Missed some languages

### ISSUE THREAD

**Issue by pangdeskpad** [baby-markt/deepl-php-lib#10]
Missed some supported languages such as "ZH", "JA", "PL". Actually these are supported by DeepL and could you update asap ?

I checked your source code and its easy i think ;)
![image](https://user-images.githubusercontent.com/28949574/83237784-4f66a400-a14a-11ea-95e6-31b25bf947a4.png)

**Comment by jkrusy** [comment]
ZH and JA have been added recently with #9
