### ISSUE TITLE
The API version must be specified

### ISSUE THREAD

**Issue by tamr** [baby-markt/deepl-php-lib#13]
I was getting an authentication error: "Authorization failed. Please supply a valid auth_key parameter." and was waiting for it to become "activated", lol.

Since v2 is now the default API version, it must be specified:
$deepl   = new DeepL($authKey, 2);

**Comment by arkadiusjonczek** [comment]
See https://github.com/Baby-Markt/deepl-php-lib/pull/14

**Comment by VimS** [comment]
Just pushed a new Version 1.1.0 where Api v2 is the default.
Thanks @arkadiusjonczek :+1:
