### ISSUE TITLE
The Response seems to not be valid JSON

### ISSUE THREAD

**Issue by jatniel** [Baby-Markt/deepl-php-lib#36]
Error, two translations in each interaction of a foreach. 
(Laravel Framework, PHP 8)

my function, for the translation:
```
    public function translation($text)
    {
        $deepl   = new DeepL($this->authKey,2,'api.deepl.com');

        $translate = $deepl->translate($text, 'en', 'fr');

        return $translate[0]['text'];
    }

```

**Comment by u-nik** [comment]
Hi @jatniel 

Unfortunately, I cannot reproduce the problem with the given information. Please tell us the steps that lead to the error so that we can reproduce the problem.

Greetings,
Niklas
