### ISSUE TITLE
Compatibility with PHP >8.1

### ISSUE THREAD

**Issue by iec989** [Baby-Markt/deepl-php-lib#38]
I'm getting the following when running composer update:
`babymarkt/deepl-php-lib[v3.0.0, ..., v3.1.0] require php >=7.3 <8.1 -> your php version (8.1.2) does not satisfy that requirement.`

**Comment by VimS** [comment]
We are aware of the compatibility issue. As you can see, the build of this pull-requests fails: 
https://github.com/Baby-Markt/deepl-php-lib/pull/37/checks?check_run_id=5454105705
We hope to start working on it in our next Sprint which will start in 12 days.

**Comment by VimS** [comment]
https://github.com/Baby-Markt/deepl-php-lib/pull/40 should take care of this.

**Comment by seifti** [comment]
Thanks @VimS - is there any ETA for the release to be done? So I can run composer update
